::: {.callout-note collapse="true" icon=false appearance="simple"}
## [03] Functional rarity: From detection to conservation
<hr />

{{< fa calendar-days >}}&nbsp; October 2024
<br/>{{< fa user >}}&nbsp; **Cyrille VIOLLE** (CEFE-CNRS, Montpellier, France)
<br/>{{< fa globe >}}&nbsp; [FREE 1](https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/free/) project

<br/>

**Abstract**

Rarity has always fascinated conservation and evolutionary biologists with the goal to uncover species characteristics causing extinction risk. Recently, some results suggest that rare species may over-contribute to the diversity of traits within communities thus supporting irreplaceable roles while others show that rare species are functionally redundant with common species. Beyond the rarity of species, the rarity of functions played by species, coined as functional rarity, is thus key to understand the impact of biodiversity decline on ecosystem functioning. However, functional rarity still lacks a clear definition and a quantitative framework while its emergence and maintenance within communities is largely unknown.<br/>
As part of the FRB-CESAB [FREE 1](https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/free/) working group, we have contributed to advance the concept of functional rarity and examine the causes and consequences of functional rarity from local to global scales. We showed that common assumptions notwithstanding, rare species can play unique and essential ecological roles, and that ecologically rare species are already more threatened by humans than ecologically common species and will be more impacted by future climate change. Finally, we highlighted that, in most taxonomic groups, hotspots of functional rarity differ from the areas where the most vulnerable species are found. This has major implications for species and ecosystem conservation where functional rarity appears to be an additional criterion to be considered urgently for the establishment of lists of so-called species at risk and for deciding on the location and size of areas to be protected.

<br/>

**Talk**

<iframe width="640" height="360" src="https://www.youtube.com/embed/iVXsPGWIPrY" title="Cesabinar #3 - FREE 1" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
:::
