::: {.callout-note collapse="true" icon=false appearance="simple"}
## [07] Inland navigation infrastructures and biodiversity: impacts and opportunities for waterwayscape management
<hr />

{{< fa calendar-days >}}&nbsp; March 2025
<br/>{{< fa user >}}&nbsp; **Alienor JELIAZKOV** (Univ. of Paris-Saclay & INRAE, France)
<br/>{{< fa user >}}&nbsp; **Aaron SEXTON** (Cornell University, USA)
<br/>{{< fa user >}}&nbsp; **Jean-Nicolas BEISEL** (Strasbourg Univ., ENGEES & CNRS, France)
<br/>{{< fa globe >}}&nbsp; [NAVIDIV](https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/navidiv/) project

<br/>

**Abstract**

Facing global change, inland navigation transport is considered as one of the most promising, sustainable transport alternatives to help operate the world ecological transition and achieve climate neutrality. Waterways thus must develop their infrastructures to promote green transport alternatives. However, ecomorphological modifications of rivers will affect biodiversity status and resilience. With the stated objective to sustainable management of waterways, the question therefore remains: what are the impacts of inland navigation on biodiversity, and how to mitigate them? ​

Cues currently available to solve this question rely on scattered case studies whose results are highly context- and scale-dependent. In addition, our knowledge of the processes driving navigation- biodiversity relationships is still limited and requires further research. We thus realised a synthesis project to study the relationships between navigation activity, the associated Inland Navigation Infrastructures (INIs), and biodiversity across different contexts and scales.

Our specific aims are to: (i) Quantify and hierarchize the effects of navigation and INIs on taxonomic and functional biodiversity; (ii) Evaluate the context-dependency and scale-dependency of the INIs-biodiversity ​ relationships; (iii) Assess the potential of restoration plans in mitigating navigation pressures. ​

This work provides impact assessment and synthetic knowledge, offering guidelines on how to prioritize management and restoration actions depending on the context and on which scales to conceive policies that ensure consistency across territories.
<br/>

**Talk**

_Exceptionally, this presentation has not been recorded._
:::
